version: "3.2"

services:
  db:
    image: postgres:10-alpine
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql

  app:
    build: .
    command: scripts/main.sh
    volumes:
      - /opt/thapakazi/share/rubygems/:/bundle_path
      - $PWD:/app
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - .docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80 #sudo setcap cap_net_bind_service=+ep `which docker-compose`
    depends_on:
      - app
      
    
    
